apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  grafana.server: |
    grafana.dialecthub.net:53 {
        hosts {
            149.56.132.188 grafana.dialecthub.net
            fallthrough
        }
    }
  staging.server: |
    staging.dialecthub.net:53 {
        hosts {
            149.56.132.188 staging.dialecthub.net
            fallthrough
        }
    }
  victorialogs.server: |
    victorialogs.dialecthub.net:53 {
        hosts {
            149.56.132.188 victorialogs.dialecthub.net
            fallthrough
        }
    }